### ISSUE TITLE
mapbox-cli-py Does Not Install on Sierra 10.12.5 via Homebrew

### ISSUE THREAD

**Issue by maptechnica** [mapbox/homebrew-cli#4]
I'm trying to install mapbox-cli-py via Homebrew.  I keep getting an error:

```
Last 15 lines from /Users/ixnayus/Library/Logs/Homebrew/mapbox/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/tmp/mapbox--homebrew-virtualenv-20170524-17337-xo75hj/target
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/mapbox/homebrew-cli/issues

```
I've tried this on two different computers, and I get the same error.

I've ensured Homebrew is upgraded and up to date as of 5/24/17 

Versions:

- Sierra 10.12.5
- Homebrew 1.2.1
- Python 2.7
- Python3 3.6.1
- pip 9.0.1
- setuptools 32.1.0 from /usr/local/lib/python2.7/site-packages (Python 2.7)

**Comment by sgillies** [comment]
@maptechnica I've seen similar reports around the web and I think your homebrew python needs to be fixed. See https://github.com/Homebrew/homebrew-python/issues/216 or https://github.com/Homebrew/homebrew-python/issues/365.
